// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";

import CampaignController from "./campaign_controller";
application.register("campaign", CampaignController);

import ChildVaccinationController from "./child_vaccination_controller";
application.register("child-vaccination", ChildVaccinationController);

import ConnectivityController from "./connectivity_controller";
application.register("connectivity", ConnectivityController);

import OfflineCampaignController from "./offline_campaign_controller";
application.register("offline-campaign", OfflineCampaignController);

import VaccinationController from "./vaccination_controller";
application.register("vaccination", VaccinationController);
