// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";

import CheckAllController from "./check_all_controller";
application.register("check-all", CheckAllController);

import GovukAccordionController from "./govuk_accordion_controller";
application.register("govuk-accordion", GovukAccordionController);

import GovukButtonController from "./govuk_button_controller";
application.register("govuk-button", GovukButtonController);

import GovukCharacterCountController from "./govuk_character_count_controller";
application.register("govuk-character-count", GovukCharacterCountController);

import GovukCheckboxesController from "./govuk_checkboxes_controller";
application.register("govuk-checkboxes", GovukCheckboxesController);

import GovukHeaderController from "./govuk_header_controller";
application.register("govuk-header", GovukHeaderController);

import GovukSkipLinkController from "./govuk_skip_link_controller";
application.register("govuk-skip-link", GovukSkipLinkController);

import NhsukErrorSummaryController from "./nhsuk_error_summary_controller";
application.register("nhsuk-error-summary", NhsukErrorSummaryController);

import NhsukHeaderController from "./nhsuk_header_controller";
application.register("nhsuk-header", NhsukHeaderController);

import NhsukNotificationBannerController from "./nhsuk_notification_banner_controller";
application.register(
  "nhsuk-notification-banner",
  NhsukNotificationBannerController,
);

import NhsukRadiosController from "./nhsuk_radios_controller";
application.register("nhsuk-radios", NhsukRadiosController);

import NhsukTabsController from "./nhsuk_tabs_controller";
application.register("nhsuk-tabs", NhsukTabsController);
