version: 2

updates:
  - package-ecosystem: bundler
    directory: /
    target-branch: next
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    target-branch: next
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /
    target-branch: next
    schedule:
      interval: weekly
