env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:cypress/recommended
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - cypress
rules: {}
