repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.99.0
    hooks:
      - id: terraform_fmt
        files: \.(tf|tfvars|hcl)$
  - repo: local
    hooks:
      - id: prettier
        name: Prettier
        entry: yarn prettier --write --ignore-unknown
        language: system
