repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.99.0
    hooks:
      - id: terraform_fmt
        files: \.(tf|tfvars|hcl)$
      - id: terraform_tflint
        args:
          - --args=--config=__GIT_WORKING_DIR__/terraform/.tflint.hcl
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: \.(enc|erb)$
      - id: end-of-file-fixer
        exclude: \.(enc|erb|csv|svg|rladr)$
      - id: check-json
      - id: check-added-large-files # Default is fail on files larger than 500kB
      - id: mixed-line-ending
        args: [--fix=lf] # Ensure all line endings are LF
        exclude: \.csv$
  - repo: local
    hooks:
      - id: prettier
        name: Prettier
        entry: yarn prettier --write --ignore-unknown
        language: system
      - id: rubocop
        name: Rubocop
        entry: bin/bundle exec rubocop --autocorrect-all
        language: system
        files: ^app/
        types: [ruby]
      - id: rufo
        name: Rufo
        entry: bin/bundle exec rufo
        language: system
        files: .erb$
        exclude: .*/layouts/[^/]*$
      - id: brakeman
        name: Brakeman
        entry: bin/bundle exec brakeman --no-pager .
        language: system
        always_run: true
        pass_filenames: false
        stages: [manual]
