inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml
    - config/rspec.yml

inherit_from:
  - node_modules/@prettier/plugin-ruby/rubocop.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - scratchpad/*

Layout/EmptyLineAfterMagicComment:
  Enabled: true

Rails/UnknownEnv:
  Environments:
    - development
    - production
    - staging
    - test

RSpec/ContextWording:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/ImplicitExpect:
  EnforcedStyle: should

RSpec/VerifiedDoubles:
  Exclude:
    - spec/controllers/concerns/consent_form_mailer_concern_spec.rb
    - spec/controllers/concerns/triage_mailer_concern_spec.rb
    - spec/controllers/concerns/vaccination_mailer_concern_spec.rb

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always_true
