organisation:
  ods_code: RLVTRN

team:
  workgroup: rollovertraining
  name: Rollover Training
  email: rollover@example.com
  phone: 01234 567890
  careplus_venue_code: ROLLOVER
  privacy_notice_url: https://www.example.com/privacy-notice
  privacy_policy_url: https://www.example.com/privacy-policy

programmes: [flu, hpv, menacwy, mmr, td_ipv]

subteams:
  generic:
    name: Rollover Training
    email: rollover@example.com
    phone: 01234 567890

users:
  - email: nurse.rollover@example.com
    password: nurse.rollover@example.com
    given_name: Nurse
    family_name: ROLLOVER

schools:
  generic:
    # Primary schools
    - 115529
    - 131806
    - 145212
    - 118853
    # Secondary schools
    - 145482
    - 137236
    - 136642
    - 135970

clinics:
  generic:
    - name: Rollover Training Hospital
