name: Reusable Deploy Workflow

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  copilot:
    name: AWS Copilot

    permissions:
      id-token: write
      contents: read

    environment:
      name: ${{ inputs.environment }}
      url: https://${{ steps.host-name.outputs.value }}

    concurrency:
      group: ${{ inputs.environment }}
      cancel-in-progress: true

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::393416225559:role/GitHubActionsRole
          aws-region: eu-west-2

      - name: Install and Verify AWS Copilot
        run: |
          curl -Lo /tmp/copilot https://github.com/aws/copilot-cli/releases/latest/download/copilot-linux
          chmod +x /tmp/copilot
          mv /tmp/copilot /usr/local/bin/copilot
          copilot --version

      - name: Deploy the application using AWS Copilot
        run: |
          copilot svc deploy --name webapp --env ${{ inputs.environment }}

      - name: Get host name
        id: host-name
        run: |
          if [ "${{ inputs.environment }}" = "pentest" ]; then
            echo "value=pentest" >> $GITHUB_OUTPUT
          else
            echo "value=$(copilot svc show --name webapp --json | jq -r '.variables[] | select(.name == "MAVIS__HOST") | select(.environment == "${{ inputs.environment }}") | .value')" >> $GITHUB_OUTPUT
          fi
