name: 'Run Test Suites Check'
description: 'Determines whether Rails test suites should run based on changed files'

inputs:
  base-ref:
    description: 'Base ref for comparison'
    required: false
    default: ${{ github.event.pull_request.base.ref }}

outputs:
  run-test-suites:
    description: 'Whether to run test suites (true/false)'
    value: ${{ steps.check.outputs.run-test-suites }}

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Determine if rails tests are needed
      id: check
      shell: bash
      run: |
        if [ "${{ github.event_name }}" == "pull_request" ]; then
          git fetch origin
          RELEVANT_DIRS=$(git diff origin/${{ inputs.base-ref }}...HEAD --name-only)
          if [ -z "$(echo "$RELEVANT_DIRS" | egrep -v '^(.github|adr|aws|docs|storage)/')" ]; then
            echo "No relevant changes detected, skipping rails tests"
            echo "run-test-suites=false" >> $GITHUB_OUTPUT
            exit 0
          fi
        fi
        echo "Not a pull request or detected relevant changes: Running rails tests"
        echo "run-test-suites=true" >> $GITHUB_OUTPUT

    - name: Handle check failure
      if: steps.check.outcome == 'failure'
      shell: bash
      run: echo "run-test-suites=true" >> $GITHUB_OUTPUT
