require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/campaigns/:campain_id/children", type: :request do
  let(:school) do
    School.create!(
      {
        urn: "130877",
        name: "St Andrew's Benn CofE (Voluntary Aided) Primary School",
        address: "Chester Street",
        locality: "",
        town: "Rugby",
        county: "Warwickshire",
        postcode: "CV21 3NX",
        minimum_age: "3",
        maximum_age: "11",
        url: "www.standrewsbennprimary.co.uk/",
        phase: "Primary",
        type: "Local authority maintained schools",
        detailed_type: "Voluntary aided school"
      }
    )
  end

  let(:child) do
    Child.create!(
      {
        first_name: "Gianna",
        last_name: "Becker",
        dob: "2017-06-27T13:33:41.428Z",
        nhs_number: "2490559432",
        gp: "Local GP",
        screening: "Approved for vaccination"
      }
    )
  end

  let(:campaign) do
    Campaign.create!({ location: school, type: "HPV", children: [child] })
  end

  let(:invalid_attributes) do
    skip("Add a hash of attributes invalid for your model")
  end

  describe "GET /index" do
    it "renders a successful response" do
      # Child.create! valid_attributes
      get campaign_vaccinations_url(campaign.id)
      expect(response).to be_successful
    end
  end
end
