{
 "title": "Database Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environment",
    "query": "sandbox-alpha, sandbox-beta, qa, test, training, preview"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "DBClusterIdentifier": "mavis-$environment", "Role": "*" },
     "expression": "SELECT CPUUtilization FROM \\\"AWS/RDS\\\"",
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "sql": {
      "from": { "property": { "name": "AWS/RDS", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "property": { "name": "Role", "type": "string" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "CPUUtilization", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "mavis-$environment" }, "property": { "name": "DBClusterIdentifier", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(CPUUtilization) FROM \"AWS/RDS\" WHERE DBClusterIdentifier = 'mavis-$environment' GROUP BY Role",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "ACU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "DBClusterIdentifier": "mavis-$environment", "Role": "*" },
     "label": "ACUs",
     "metricName": "ServerlessDatabaseCapacity",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Freeable Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dimensions": { "DBClusterIdentifier": "mavis-$environment", "Role": "*" },
     "metricName": "FreeableMemory",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Database Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "DBClusterIdentifier": "mavis-$environment", "Role": "*" },
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Read/Write IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "dimensions": { "DBClusterIdentifier": "mavis-$environment", "Role": "*" },
     "metricName": "ReadIOPS",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "statistic": "Average"
    },
    {
     "dimensions": { "DBClusterIdentifier": "mavis-$environment", "Role": "WRITER" },
     "metricName": "WriteIOPS",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Read/Write Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "dimensions": { "DBClusterIdentifier": "mavis-$environment", "Role": "*" },
     "metricName": "ReadLatency",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "statistic": "Average"
    },
    {
     "dimensions": { "DBClusterIdentifier": "mavis-$environment", "Role": "WRITER" },
     "metricName": "WriteLatency",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "statistic": "Average"
    }
   ]
  }
 ]
}