Parameters:
  App:
    Type: String
    Description: Your application's name.
  Env:
    Type: String
    Description: The name of the environment being deployed.
  # Customize your Aurora Serverless cluster by setting the default value of the following parameters.
  dbDBName:
    Type: String
    Description: The name of the initial database to be created in the Aurora Serverless v2 cluster.
    Default: manage_vaccinations
    # Cannot have special characters
    # Naming constraints: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_Limits.html#RDS_Limits.Constraints
  VPCID:
    Type: String
    Description: The ID of the VPC in which to create the Aurora Serverless v2 cluster.
    Default: ""
  PrivateSubnets:
    Type: String
    Description: The IDs of the private subnets in which to create the Aurora Serverless v2 cluster.
    Default: ""

Mappings:
  dbEnvScalingConfigurationMap:
    staging:
      "DBMinCapacity": 0.5 # AllowedValues: from 0.5 through 128
      "DBMaxCapacity": 8 # AllowedValues: from 0.5 through 128

    All:
      "DBMinCapacity": 0.5 # AllowedValues: from 0.5 through 128
      "DBMaxCapacity": 8 # AllowedValues: from 0.5 through 128

Resources:
  dbDBSubnetGroup:
    Type: "AWS::RDS::DBSubnetGroup"
    Properties:
      DBSubnetGroupDescription: Group of private subnets for Aurora Serverless v2 cluster.
      SubnetIds: !Split [",", !Ref PrivateSubnets]

  dbWorkloadSecurityGroup:
    Metadata:
      "aws:copilot:description": "A security group for one or more workloads to access the Aurora Serverless v2 cluster db"
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "The Security Group to access Aurora Serverless v2 cluster db."
      VpcId: !Ref VPCID
      Tags:
        - Key: Name
          Value: !Sub "copilot-${App}-${Env}-Aurora"

  dbDBClusterSecurityGroup:
    Metadata:
      "aws:copilot:description": "A security group for your Aurora Serverless v2 cluster db"
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: The Security Group for the Aurora Serverless v2 cluster.
      VpcId: !Ref VPCID
      Tags:
        - Key: Name
          Value: !Sub "copilot-${App}-${Env}-Aurora"

  dbDBClusterSecurityGroupIngressFromWorkload:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: Ingress from one or more workloads in the environment.
      GroupId: !Ref dbDBClusterSecurityGroup
      IpProtocol: tcp
      ToPort: 5432
      FromPort: 5432
      SourceSecurityGroupId: !Ref dbWorkloadSecurityGroup

  dbAuroraSecret:
    Metadata:
      "aws:copilot:description": "A Secrets Manager secret to store your DB credentials"
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: !Sub Aurora main user secret for ${AWS::StackName}
      GenerateSecretString:
        SecretStringTemplate: '{"username": "postgres"}'
        GenerateStringKey: "password"
        ExcludePunctuation: true
        IncludeSpace: false
        PasswordLength: 16
  dbDBClusterParameterGroup:
    Metadata:
      "aws:copilot:description": "A DB parameter group for engine configuration values"
    Type: "AWS::RDS::DBClusterParameterGroup"
    Properties:
      Description: !Ref "AWS::StackName"
      Family: "aurora-postgresql14"
      Parameters:
        client_encoding: "UTF8"

  dbDBCluster:
    Metadata:
      "aws:copilot:description": "The db Aurora Serverless v2 database cluster"
    Type: "AWS::RDS::DBCluster"
    Properties:
      MasterUsername:
        !Join [
          "",
          [
            "{{resolve:secretsmanager:",
            !Ref dbAuroraSecret,
            ":SecretString:username}}",
          ],
        ]
      MasterUserPassword:
        !Join [
          "",
          [
            "{{resolve:secretsmanager:",
            !Ref dbAuroraSecret,
            ":SecretString:password}}",
          ],
        ]
      DatabaseName: !Ref dbDBName
      Engine: "aurora-postgresql"
      EngineVersion: "14.9"
      DBClusterParameterGroupName: !Ref dbDBClusterParameterGroup
      DBSubnetGroupName: !Ref dbDBSubnetGroup
      Port: 5432
      VpcSecurityGroupIds:
        - !Ref dbDBClusterSecurityGroup
      ServerlessV2ScalingConfiguration:
        # Replace "All" below with "!Ref Env" to set different autoscaling limits per environment.
        MinCapacity:
          !FindInMap [dbEnvScalingConfigurationMap, All, DBMinCapacity]
        MaxCapacity:
          !FindInMap [dbEnvScalingConfigurationMap, All, DBMaxCapacity]
      StorageEncrypted: true
      DeletionProtection: true # Keep this to protect the cluster from deletion. This also applies to the databases that are a part of this cluster.
      BackupRetentionPeriod: 7 # Store the snapshots for 7 days.

  dbDBWriterInstance:
    Metadata:
      "aws:copilot:description": "The db Aurora Serverless v2 writer instance"
    Type: "AWS::RDS::DBInstance"
    Properties:
      DBClusterIdentifier: !Ref dbDBCluster
      DBInstanceClass: db.serverless
      Engine: "aurora-postgresql"
      PromotionTier: 1
      AvailabilityZone: !Select
        - 0
        - !GetAZs
          Ref: AWS::Region

  dbSecretAuroraClusterAttachment:
    Type: AWS::SecretsManager::SecretTargetAttachment
    Properties:
      SecretId: !Ref dbAuroraSecret
      TargetId: !Ref dbDBCluster
      TargetType: AWS::RDS::DBCluster

Outputs:
  dbSecret:
    Description: "The JSON secret that holds the database username and password. Fields are 'host', 'port', 'dbname', 'username', 'password', 'dbClusterIdentifier' and 'engine'"
    Value: !Ref dbAuroraSecret
    Export:
      Name: !Sub ${App}-${Env}-dbAuroraSecret
  dbSecurityGroup:
    Description: "The security group to attach to the workload."
    Value: !Ref dbWorkloadSecurityGroup
    Export:
      Name: !Sub ${App}-${Env}-dbSecurityGroup
