#!/usr/bin/env bash

set -euo pipefail

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <environment>"
    exit 1
fi

environment=$1
alert_file="grafana/modules/${environment}_alerts/alerts.tf"
alert_template="${alert_file}.tpl"

{
    echo "####################################################"
    echo "# This file is auto-generated. Do not edit directly."
    echo "# It is based on ${alert_template} and generated by generate_alert_config.sh"
    echo "# Generated on: $(date -u +"%Y-%m-%d %H:%M:%S UTC")"
    echo "####################################################"
    echo ""
    cat "$alert_template"
} > "$alert_file"

# Delete org_id
sed -i '/org_id/d' "$alert_file"

# Replace 'receiver' with 'contact_point'
sed -i 's/receiver/contact_point/g' "$alert_file"

# Remove attributes with null values
sed -i '/= null/d' "$alert_file"

# Insert "disable_provenance = true" right after "resource" lines
sed -i '/^resource/ a\  disable_provenance = true' "$alert_file"