@startuml

!include <C4/C4_Context.puml>

LAYOUT_TOP_DOWN()

title "Manage vaccinations in schools context diagram"

Person_Ext(sais, "SAIS Organisation")
Person_Ext(parents, "Parents")

System(manage, "Manage vaccinations in schools", "Ruby on Rails, HTML, Javascript")

SystemDb_Ext(vaccineRecord, "Vaccination Record", "FHIR Server")
SystemDb_Ext(pds, "PDS", "")

AddRelTag("optional", $textColor="black", $lineColor="black", $lineStyle="dashed")

Rel(sais, manage, "Manage programmes")
Rel(sais, manage, "Record Child Vaccination")
Rel(parents, manage, "Consent response")
Rel(manage, vaccineRecord, "Updates Child Vaccination History", $tags="optional")
Rel(manage, pds, "NHS Number Lookup", $tags="optional")

SHOW_FLOATING_LEGEND()

@enduml
