@startuml

!include <C4/C4_Container.puml>

LAYOUT_TOP_DOWN()

title "Manage Vaccinations For School-aged Children Container View"

AddElementTag("outside_context", $bgColor="#CCC", $fontColor="#FFF")

Person_Ext(sais, "SAIS Team", $tags="outside_context")
Person_Ext(parents, "Parents", $tags="outside_context")

Boundary(aws, "AWS") {
  System_Boundary(manage, "Service", "") {
    Container(server, "Server Application", "Ruby on Rails")
  }
}

System_Ext(govukNotify, "GOVUK Notify", "Email and SMS Service")

AddRelTag("optional", $textColor="black", $lineColor="black", $lineStyle="dashed")

Rel(sais, server, "Manage campaigns")
Rel(sais, server, "Record Child Vaccination")
Rel(parents, server, "Consent response")
Rel(server, govukNotify, "Send email and SMS")

SHOW_FLOATING_LEGEND()

@enduml
