@startuml

!include <C4/C4_Deployment.puml>

title "Manage vaccinations in schools deployed view"

Boundary(aws, "AWS", "AWS") {
    Container_Ext(lb, "EC2 Load Balancers", "HTTPS, HTTP/2, TLS 1.2")

    Deployment_Node(dyno, "ECS Fargate") {
        Container(server, "Server App", "Ruby on Rails")
    }

    Deployment_Node(herokuPostgres, "RDS Aurora") {
        ContainerDb(db, "Database", "PostgreSQL")
    }
}

Deployment_Node(comp, "Customer's computer") {
    Deployment_Node(browser, "Web Browser") {
        Container(webapp, "Web Application", "HTML and JavaScript")
    }
}

Rel(lb, server, "Fetch Resources", "HTTP")
Rel(server, db, "Reads / Writes Resources", "Postgres, TLS")
Rel_L(webapp, lb, "Fetch Resources", "HTTPS")

SHOW_FLOATING_LEGEND()

@enduml
