@startuml

title Failed malicious POST with CSRF

autoactivate on

== User is still authenticated with manage.nhs.uk ==

Browser -> evil.site: GET /
return 200 OK
note right
    // Malicious form that POSTs to manage.nhs.uk
    <form action="https://manage.nhs.uk/patients/1/vaccinations" ...>
      <input type="hidden" name="vaccination" value="mmr" />
      <input type="hidden" name="vaccination_given" value="false" />
    ...
end note

Browser -> manage.nhs.uk: POST /patients/1/vaccinations
note right
    vaccine=mmr
    vaccination_given=false
end note
Browser <-[#red]-x manage.nhs.uk: 422 Unprocessable entity
deactivate manage.nhs.uk
note right #FCC
    Missing CSRF token
end note

@enduml
