@startuml

title Successful POST with CSRF

autoactivate on

Browser -> record.nhs.uk: GET /patients/1/vaccinations/new
return 200 OK

note right
    csrf="Unique CSRF Token"
end note

Browser -> record.nhs.uk: POST /patients/1/vaccinations
note right
    vaccine=mmr
    vaccination_given=true
    csrf="Unique CSRF Token"
end note
return 200 OK

@enduml
