@startuml

participant "User" as user
participant "Front-End" as frontend
participant "Service Worker" as sw
participant "Server App" as server

user -> frontend: View programme
frontend -> sw: get programme pages
sw -> server: get programme pages
sw <-- server: programme page
frontend <-- sw: programme page

user -> frontend: Record vaccination
frontend -> sw: post vaccination record
sw -> server: post vaccination record
sw <-- server: ok
frontend <-- sw: ok

@enduml
