@startuml

participant "User" as user
participant "Front-End" as frontend
participant "Service Worker" as sw
participant "Server App" as server

user -> frontend: View campaign
frontend -> sw: get campaign pages
sw -> server: get campaign pages
sw <-- server: campaign page
frontend <-- sw: campaign page

user -> frontend: Record vaccination
frontend -> sw: post vaccination record
sw -> server: post vaccination record
sw <-- server: ok
frontend <-- sw: ok

@enduml
