# Container Variables Configuration
# This file specifies environment-specific variables that will be added to or override
# the environment variables extracted from terraform configuration

environments:
  production:
    RAILS_ENV: production
    SENTRY_ENVIRONMENT: production

  qa:
    RAILS_ENV: staging
    SENTRY_ENVIRONMENT: qa

  test:
    RAILS_ENV: staging
    SENTRY_ENVIRONMENT: test

  preview:
    RAILS_ENV: staging
    SENTRY_ENVIRONMENT: preview

  training:
    RAILS_ENV: staging
    SENTRY_ENVIRONMENT: training

  sandbox-alpha:
    RAILS_ENV: staging
    SENTRY_ENVIRONMENT: sandbox-alpha

  sandbox-beta:
    RAILS_ENV: staging
    SENTRY_ENVIRONMENT: sandbox-beta

# Tunable Variables Configuration
# This section specifies environment-specific variables that will be populated into the SSM parameter store
# at /${environment}/envs/<server_type> and pulled on task startup. These variables can be modified in the cloud
# console or via the AWS CLI and picked up after tasks are restarted, reducing the need to redeploy.
tunable_vars:
  production:
    web:
      MAVIS__SPLUNK__ENABLED: "true"
      MAVIS__CIS2__ENABLED: "true"
      MAVIS__ACADEMIC_YEAR_NUMBER_OF_PREPARATION_DAYS: 31
    good-job:
      GOOD_JOB_MAX_THREADS: 5
    sidekiq:
      SIDEKIQ_CONCURRENCY: 5
      MAVIS__PDS__ENQUEUE_BULK_UPDATES: "true"
      MAVIS__PDS__RATE_LIMIT_PER_SECOND: 50

  qa:
    web:
      MAVIS__SPLUNK__ENABLED: "true"
      MAVIS__CIS2__ENABLED: "false"
      MAVIS__ACADEMIC_YEAR_NUMBER_OF_PREPARATION_DAYS: 45
    good-job:
      GOOD_JOB_MAX_THREADS: 5
    sidekiq:
      SIDEKIQ_CONCURRENCY: 5
      MAVIS__PDS__ENQUEUE_BULK_UPDATES: "false"
      MAVIS__PDS__RATE_LIMIT_PER_SECOND: 5

  test:
    web:
      MAVIS__SPLUNK__ENABLED: "true"
      MAVIS__CIS2__ENABLED: "true"
    good-job:
      GOOD_JOB_MAX_THREADS: 5
    sidekiq:
      SIDEKIQ_CONCURRENCY: 5
      MAVIS__PDS__ENQUEUE_BULK_UPDATES: "false"
      MAVIS__PDS__RATE_LIMIT_PER_SECOND: 5

  preview:
    web:
      MAVIS__SPLUNK__ENABLED: "false"
      MAVIS__CIS2__ENABLED: "false"
    good-job:
      GOOD_JOB_MAX_THREADS: 5
    sidekiq:
      SIDEKIQ_CONCURRENCY: 5
      MAVIS__PDS__ENQUEUE_BULK_UPDATES: "false"
      MAVIS__PDS__RATE_LIMIT_PER_SECOND: 5

  training:
    web:
      MAVIS__SPLUNK__ENABLED: "false"
      MAVIS__CIS2__ENABLED: "false"
    good-job:
      GOOD_JOB_MAX_THREADS: 5
    sidekiq:
      SIDEKIQ_CONCURRENCY: 5
      MAVIS__PDS__ENQUEUE_BULK_UPDATES: "false"
      MAVIS__PDS__RATE_LIMIT_PER_SECOND: 5

  sandbox-alpha:
    web:
      MAVIS__SPLUNK__ENABLED: "false"
      MAVIS__CIS2__ENABLED: "false"
    good-job:
      GOOD_JOB_MAX_THREADS: 5
    sidekiq:
      SIDEKIQ_CONCURRENCY: 5
      MAVIS__PDS__ENQUEUE_BULK_UPDATES: "false"
      MAVIS__PDS__RATE_LIMIT_PER_SECOND: 5

  sandbox-beta:
    web:
      MAVIS__SPLUNK__ENABLED: "false"
      MAVIS__CIS2__ENABLED: "false"
    good-job:
      GOOD_JOB_MAX_THREADS: 5
    sidekiq:
      SIDEKIQ_CONCURRENCY: 5
      MAVIS__PDS__ENQUEUE_BULK_UPDATES: "false"
      MAVIS__PDS__RATE_LIMIT_PER_SECOND: 5
