allow_dev_phone_numbers: true
fast_reset: true

cis2:
  issuer: "http://localhost:4000/not/used"

mesh:
  base_url: https://localhost:8700
  disable_ssl_verification: true
  mailbox: X26ABC1
  password: password
  dps_mailbox: X26ABC3
  shared_key: TestKey

pds:
  base_url: "https://sandbox.api.service.nhs.uk/personal-demographics/FHIR/R4"

nhs_api:
  base_url: "https://sandbox.api.service.nhs.uk"
  jwt_private_key: "SUPER PRIVATE KEY"
