allow_dev_phone_numbers: true
disallow_database_seeding: false
web_concurrency: 0

cis2:
  issuer: "http://localhost:4000/test/oidc"
  client_id: "31337.apps.national"

govuk_notify:
  callback_bearer_token: test-bearer-token
  enabled: false
  mode: test

nhs_api:
  base_url: "https://sandbox.api.service.nhs.uk"
  disable_authentication: true

splunk:
  enabled: false

reporting_api:
  client_app:
    root_url: http://localhost:5001/