allow_dev_phone_numbers: true
fast_reset: true

cis2:
  issuer: "http://localhost:4000/test/oidc"
  client_id: "31337.apps.national"
  enabled: true
  secret: VEWWYSEKRHET

mesh:
  base_url: https://localhost:8700
  disable_ssl_verification: true
  mailbox: X26ABC1
  password: password
  dps_mailbox: X26ABC3
  shared_key: TestKey

nhs_api:
  base_url: "https://sandbox.api.service.nhs.uk"
  disable_authentication: true

pds:
  perform_jobs: true
