allow_dev_phone_numbers: true
disallow_database_seeding: false

cis2:
  issuer: "http://localhost:4000/test/oidc"
  client_id: "31337.apps.national"
  secret: VEWWYSEKRHET

mesh:
  base_url: https://localhost:8700
  disable_ssl_verification: true
  dps_mailbox: X26ABC3
  mailbox: X26ABC1

nhs_api:
  base_url: "https://sandbox.api.service.nhs.uk"
  disable_authentication: true
