:imagesdir: images
:source-highlighter: pygments

ifdef::env-github[]
// If on GitHub, define attributes so we can find our diagram files and render
// them.

// The branch will be used to find the correct diagrams to render below.
// When PRing changes to the diagrams you can change this attributes
// temporarily to the name of the branch you're working on. But don't forget
// to change it back to main before merging!!
:github-branch: main

:github-repo: nhsuk/record-childrens-vaccinations

// URL for PlantUML Proxy. Using an attribute mainly because it's just tidier.
:plantuml-proxy-url: http://www.plantuml.com/plantuml/proxy?cache=no&src=

// Full path prefix we'll use for diagrams below.
:diagram-path-url: {plantuml-proxy-url}https://raw.githubusercontent.com/{github-repo}/{github-branch}/docs
endif::[]

:toc:

= Architecture

:sectnums:
:sectnumlevels: 2

== Introduction and Goals

This is the pilot a service to manage vaccinations in schools and during
catch-up clinics. This service will provide e-consent, programme management and
point-of-care services for SAIS teams and parents. The goal is for this service
to integrate with the national vaccination record to record vaccinations.

This service is in Alpha and this pilot is being used in to explore designs and
further our understandings of user requirements through user research.
Requirements have been tailored to focus on user-facing features over
non-functional requirements which have been, where possible, de-emphasised.

=== Requirements Overview

.Functional Requirements

* Allow SAIS teams to deliver vaccination programmes.
** Manage vaccination programmes including location and cohort information.
** Create consent invites.
** Record vaccinations administered.
* Allow parents to respond to consent requests.
* Operate in settings where there is no Internet access, i.e. offline working.

.Non-Functional Requirements

* Security
** Simple authentication and authorisation model; the alpha team will issue
   individual logins, tied to email addresses, to each SAIS user.
** Security model appropriate for scale of experiment
*** Each SAIS team will only be able to view and record vaccinations/patients
    for the school sessions that they manage
*** The service will be available on the public internet with no IP address
    range restrictions
** No integration with NHS CIS 2 or other SSO provider, this isn't required yet
* Rapid development
** Cloud-based deployment
** CI & CD for fast and stable deployment
** Web application framework that enables accelerated delivery
* Data persistence
** Data persisted between sessions and users
** No long term data storage, i.e. beyond end of testing phase(s)
** Support for offline functionality
* Integration with NHS services (where possible)
** Send events to National Vaccination Record
** Use Personal Demographic Service (PDS) to perform NHS number lookup

We won't need:

* Scalability
* Authentication that's integrated with wider NHS or other SSO provider
* Reporting capability
* Long term maintainability of codebase
* Long term storage of data

<<<<
== Architecture Constraints

* The system must protect patient data and comply with all applicable laws and
  regulations.
* The system will adhere to the applicable NHS architecture and design
  principles.
* The system must be deployed to a cloud platform, but also be platform agnostic
  and not constrained to run on any one cloud platform.
* The system must be deployed to NHS approved platforms.

Additionally, there are some integrations which will be required in the
production service, but which we consider optional while in Alpha. Where
possible we will try to integrate with these services, but not treat it as a
blocker if we cannot:

* National vaccination record service, to update the vaccination record for
  the patient. We do not yet know what this system looks like so it is unlikely
  we'll be able to integrate with it properly. However we anticipate that
  whatever this system is, it will have a FHIR API which we can use to update
  the vaccination record. As this is a convenient technical abstraction point
  for whatever the future system is, we will demonstrate that we can update a
  FHIR API when an vaccination is administered as a proof of concept in this
  Alpha.
* The Personal Demographic Service (PDS) will be used to look up patient's NHS
  numbers using their name and date of birth. Because we are using real patient
  data from a non-live service, there may be serious hurdles to integrating with
  PDS, and we may need to drop this requirements or opt for a mock server if we
  think that will be beneficial.

<<<<
== System Scope and Context

ifdef::env-github[]
image::{diagram-path-url}/diagrams/context-view-future.puml[Context view diagram]
endif::[]

ifndef::env-github[]
[plantuml,align="center"]
----
include::diagrams/context-view-future.puml[]
----
endif::[]

SAIS Team::
Team responsible for performing vaccinations on school-aged children.

Parents::
Parents are notified of the planned vaccination programme and invited to give
consent for their children to be vaccinated.

Manage vaccinations in schools service::
The service will be used by the SAIS team to record vaccinations.

Vaccination Record::

Service which will hold a record of vaccinations for citizens across the NHS.
This service is currently being designed and it's final form is yet to be
determined, however any new service created will very likely use a Rest
FHIR API.
+
However, it is possible that in the interim this service will be DPS, which is
built using Data Bricks and which uses file transfers for data input and output,
so may present additional challenges.
+
This integration may not be available during during this alpha.

PDS (Personal Demographics Service)::
Service which will allow us to look up NHS numbers for patients who don't know
theirs. Crucial for properly identifying patients.
+
This integration may not be available during during this alpha.

== Solution strategy

Certain solution strategy decisions are recorded as architecture decisions in
the Architecture Decision Records (ADRs), which can be found in link:../adr/[the
`adr` directory at the root of this repository]. Relevant ADRs:

* link:../adr/00002-begin-with-a-monolithic-application-architecture.md[ADR 2:
  Application Architecture]
* link:../adr/00004-language-and-framework.md[ADR 4: Language and framework]

== Building Blocks View

=== Level 1: Container View

ifdef::env-github[]
image::{diagram-path-url}/diagrams/container-view-future.puml[Container view diagram]
endif::[]

ifndef::env-github[]
[plantuml,align="center"]
----
include::diagrams/container-view-future.puml[]
----
endif::[]

GOVUK Notify::
This service used to send consent confirmations and other notifications to
parents. It is an external service run by Government Digital Service (GDS) and
in use by other NHS services.

=== Level 2: Component View

ifdef::env-github[]
image::{diagram-path-url}/diagrams/component-view-future.puml[Component view diagram]
endif::[]

ifndef::env-github[]
[plantuml,align="center"]
----
include::diagrams/component-view-future.puml[]
----
endif::[]

Browser Cache Storage::
Data necessary for offline functionality is stored in the browser's cache
storage. This is managed by the service worker, see the offline documentation
for more information.

Database::
Relational storage used to store application data including programme data,
consent responses and vaccination events. In the case of the vaccination events,
this data would be uploaded to the national vaccination record and this data
store would be used as temporary storage. However during the alpha phase
uploading to the national vaccination record may not available, so the
vaccination event data may be kept in this store until the end of the pilot.

== Runtime View

The Manage vaccinations in schools service is built largely as a
standard server-rendered web application: HTML pages are rendered on the server
and delivered along with CSS and JavaScript to the client. Users login to the
service using a standard login page, and as is standard with Ruby on Rails apps,
resources are exposed with REST-like paths using an MVC approach to separate
concerns on the server.

There is a notable exception made to this pattern, though, to support offline
working.

=== Offline support

include::offline-support.adoc[leveloffset=+2,lines=24..-1]

== Deployment

include::deployment.adoc[leveloffset=+1,lines=24..-1]

== Components

* Authentication
* Programme management - creation, update, etc
* Programme operations and vaccination recording
* Offline support - Browser-based component
* FHIR server synchronisation
