:imagesdir: images
:source-highlighter: pygments

ifdef::env-github[]
// If on GitHub, define attributes so we can find our diagram files and render
// them.

// The branch will be used to find the correct diagrams to render below.
// When PRing changes to the diagrams you can change this attributes
// temporarily to the name of the branch you're working on. But don't forget
// to change it back to main before merging!!
:github-branch: main

:github-repo: nhsuk/record-childrens-vaccinations

// URL for PlantUML Proxy. Using an attribute mainly because it's just tidier.
:plantuml-proxy-url: http://www.plantuml.com/plantuml/proxy?cache=no&src=

// Full path prefix we'll use for diagrams below.
:diagram-path-url: {plantuml-proxy-url}https://raw.githubusercontent.com/{github-repo}/{github-branch}/docs
endif::[]

:toc:

= Architecture

:sectnums:
:sectnumlevels: 2

== Introduction and Goals

This is the prototype a service to manage vaccinations for school-aged children
in schools and during catch-up clinics. This service will provide e-consent,
campaign management and point-of-care services for SAIS teams and parents. The
goal is for this service to integrate with the national vaccination record to
record vaccinations. However, integration with the national vaccination record
will not be part of this phase.

This service is in Alpha and this pilot is being used in to explore designs and
further our understandings of user requirements through user research.
Requirements have been tailored to focus on user-facing features over
non-functional requirements which have been, where possible, de-emphasised.

=== Requirements Overview

.Functional Requirements

* Allow SAIS teams to deliver vaccination campaigns.
** Manage vaccination campaigns including location and cohort information.
** Create consent invites.
** Record vaccinations administered.
* Allow parents to respond to consent requests.

.Non-Functional Requirements

* Security
** Simple authentication and authorisation model; the alpha team will issue
   individual logins, tied to email addresses, to each SAIS user.
** Security model appropriate for scale of experiment
*** Each SAIS team will only be able to view and record vaccinations/patients
    for the school sessions that they manage
*** The service will be available on the public internet with no IP address
    range restrictions
** No integration with NHS CIS 2 or other SSO provider, this isn't required yet
* Rapid development
** Cloud-based deployment
** CI & CD for fast and stable deployment
** Web application framework that enables accelerated delivery
* Data persistence
** Data persisted between sessions and users
** No long term data storage, i.e. beyond end of testing phase(s)

We won't need:

* Scalability
* Authentication that's integrated with wider NHS or other SSO provider
* Reporting capability
* Long term maintainability of codebase
* Offline functionality
* Long term storage of data
* Integration with NHS services
** Send events to National Vaccination Record
** Use Personal Demographic Service (PDS) to perform NHS number lookup

<<<<
== Architecture Constraints

* The system must protect patient data and comply with all applicable laws and
  regulations.
* The system will adhere to the applicable NHS architecture and design
  principles.
* The system must be deployed to a cloud platform, but also be platform agnostic
  and not constrained to run on any one cloud platform.
* The system must be deployed to NHS approved platforms.

Additionally, there are some integrations which will be required in the
production service, but which we will be descoped for the current phase. They
are listed here to help define the wider goal of this service. These services
are:

* National vaccination record service, to update the vaccination record for
  the patient. We do not yet know what this system looks like so it is unlikely
  we'll be able to integrate with it properly. However we anticipate that
  whatever this system is, it will have a FHIR API which we can use to update
  the vaccination record. As this is a convenient technical abstraction point
  for whatever the future system is, we will demonstrate that we can update a
  FHIR API when an vaccination is administered as a proof of concept in this
  Alpha.
* The Personal Demographic Service (PDS) will be used to look up patient's NHS
  numbers using their name and date of birth. Because we are using real patient
  data from a non-live service, there may be serious hurdles to integrating with
  PDS, and we may need to drop this requirements or opt for a mock server if we
  think that will be beneficial.

<<<<
== System Scope and Context

ifdef::env-github[]
image::{diagram-path-url}/diagrams/context-view.puml[Context view diagram]
endif::[]

ifndef::env-github[]
[plantuml,align="center"]
----
include::diagrams/context-view.puml[]
----
endif::[]

SAIS Team::
Team responsible for performing vaccinations on school-aged children.

Parents::
Parents are notified of the planned vaccination campaign and invited to give
consent for their children to be vaccinated.

Manage vaccinations for school-aged children Service::
The service will be used by the SAIS team to record vaccinations.

== Solution strategy

Certain solution strategy decisions are recorded as architecture decisions in
the Architecture Decision Records (ADRs), which can be found in link:../adr/[the
`adr` directory at the root of this repository]. Relevant ADRs:

* link:../adr/00002-begin-with-a-monolithic-application-architecture.md[ADR 2:
  Application Architecture]
* link:../adr/00004-language-and-framework.md[ADR 4: Language and framework]

== Building Blocks View

=== Level 1: Container View

ifdef::env-github[]
image::{diagram-path-url}/diagrams/container-view.puml[Container view diagram]
endif::[]

ifndef::env-github[]
[plantuml,align="center"]
----
include::diagrams/container-view.puml[]
----
endif::[]

GOVUK Notify::
This service used to send consent confirmations and other notifications to
parents. It is an external service run by Government Digital Service (GDS) and
in use by other NHS services.

=== Level 2: Component View

ifdef::env-github[]
image::{diagram-path-url}/diagrams/component-view.puml[Component view diagram]
endif::[]

ifndef::env-github[]
[plantuml,align="center"]
----
include::diagrams/component-view.puml[]
----
endif::[]

Database::
Relational storage used to store application data including campaign data,
consent responses and vaccination events. In the case of the vaccination events,
this data would be uploaded to the national vaccination record and this data
store would be used as temporary storage. However during the alpha phase
uploading to the national vaccination record may not available, so the
vaccination event data may be kept in this store until the end of the pilot.

Sending email and SMS::
For the current scale of this pilot the sending of emails will be done directly
from the web servers. It is common for services to use separate workers to
process API integration with external services to isolate the web application
from possible network issues, but won't be necessary with the number of users
using the pilot.

== Runtime View

The Manage vaccinations for school-aged children service is built largely as a
standard server-rendered web application: HTML pages are rendered on the server
and delivered along with CSS and JavaScript to the client. Users login to the
service using a standard login page, and as is standard with Ruby on Rails apps,
resources are exposed with REST-like paths using an MVC approach to separate
concerns on the server.

== Deployment

include::deployment.adoc[leveloffset=+1,lines=24..-1]

== Components

* Authentication
* Campaign management - creation, update, etc
* Campaign operations and vaccination recording
* Offline support - Browser-based component
* FHIR server synchronisation
