@startuml

!include <C4/C4_Context.puml>

LAYOUT_TOP_DOWN()
LAYOUT_WITH_LEGEND()

title Record Children's Vaccination Business Context Overview

Person(sais, "SAIS Team")
Person_Ext(parents, "Parents")

System(record, "Record Children's Vaccination", "")
SystemDb(vaccineRecord, "Vaccination Record", "FHIR Server")
SystemDb(pds, "PDS")

System_Ext(notify, "GOV.UK Notify")

Rel(sais, record, "Manages campaigns")
Rel(sais, record, "Records Child Vaccination")
Rel(parents, record, "Consent response")
Rel(record, vaccineRecord, "Updates Child Vaccination History")
Rel(record, pds, "Requests Patient Details")t
Rel(record, notify, "Send consent notifications", "Rest API")
Rel_U(notify, parents, "Consent notification", "Email")

@enduml
