:imagesdir: images
:source-highlighter: pygments

ifdef::env-github[]
// If on GitHub, define attributes so we can find our diagram files and render
// them.

// The branch will be used to find the correct diagrams to render below.
// Change this when working on updates to the diagrams and want the new ones
// reflected on GitHub, e.g. on a PR.
:github-branch: add-offline-docs

:github-repo: nhsuk/record-childrens-vaccinations

// URL for PlantUML Proxy. Using an attribute mainly because it's just tidier.
:plantuml-proxy-url: http://www.plantuml.com/plantuml/proxy?cache=no&src=

// Full path prefix we'll use for diagrams below.
:diagram-path-url: {plantuml-proxy-url}https://raw.githubusercontent.com/{github-repo}/{github-branch}/docs
endif::[]

# Offline CSRF Security

## CSRF Security

Normally a CSRF token protects from cross-site attacks by ensuring that the data
being submitted is coming from a trusted source. See the
https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy#how_to_block_cross-origin_access[MDN documentation]
for more info on the browser's cross-origin policy. This means that the
submitted form was generated by the trusted website, i.e. the same site that the
form is being submitted to, and not by a different site using a malicious
payload.

To illustrate, a normal interaction with valid CSRF looks like this:

ifdef::env-github[]
image::{diagram-path-url}/diagrams/successful-post-with-csrf.puml[Successful POST with CSRF diagram]
endif::[]

ifndef::env-github[]
[plantuml,align="center"]
----
include::diagrams/successful-post-with-csrf.puml[]
----
endif::[]

Then if a malicious site tries to piggy-back on the browser's already-established
session, they would not have access to the unique CSRF token and would not be
able to submit a malicious payload:

ifdef::env-github[]
image::{diagram-path-url}/diagrams/failed-malicious-post-with-csrf.puml[Failed malicious POST with CSRF diagram]
endif::[]

ifndef::env-github[]
[plantuml,align="center"]
----
include::diagrams/failed-malicious-post-with-csrf.puml[]
----
endif::[]

## Offline Mode

When working offline, however, the form used to submit the vaccinations data is
generated before going offline, and then submitted once the browser is back
online. This triggers CSRF protection because the CSRF token is, most likely, no
longer valid after the browser has been offline for some time:

ifdef::env-github[]
image::{diagram-path-url}/diagrams/failed-offline-post-with-outdated-csrf.puml[Failed offline POST with outdated CSRF diagram]
endif::[]

ifndef::env-github[]
[plantuml,align="center"]
----
include::diagrams/failed-offline-post-with-outdated-csrf.puml[]
----
endif::[]

The simplest way to make this work is to remove the need for a CSRF token altogether:

ifdef::env-github[]
image::{diagram-path-url}/diagrams/successful-offline-post-without-csrf.puml[Successful offline POST without CSRF diagram]
endif::[]

ifndef::env-github[]
[plantuml,align="center"]
----
include::diagrams/successful-offline-post-without-csrf.puml[]
----
endif::[]

But that opens us up to malicious actors:

ifdef::env-github[]
image::{diagram-path-url}/diagrams/malicious-offline-post-without-csrf.puml[Malicious offline POST without CSRF diagram]
endif::[]

ifndef::env-github[]
[plantuml,align="center"]
----
include::diagrams/malicious-offline-post-without-csrf.puml[]
----
endif::[]

To secure this, we need to re-introduce a way to get a CSRF token through a GET
request to record.nhs.uk. Doing a GET request from JS on a page from evil.site
will trigger cross-site scripting protection in modern browsers:

ifdef::env-github[]
image::{diagram-path-url}/diagrams/successful-offline-post-with-csrf.puml[Successful offline POST with CSRF diagram]
endif::[]

ifndef::env-github[]
[plantuml,align="center"]
----
include::diagrams/successful-offline-post-with-csrf.puml[]
----
endif::[]

And now when the attacker attempts to submit the form they are missing the required CSRF token:

ifdef::env-github[]
image::{diagram-path-url}/diagrams/failed-malicious-offline-post-without-csrf.puml[Failed malicious offline POST without CSRF diagram]
endif::[]

ifndef::env-github[]
[plantuml,align="center"]
----
include::diagrams/failed-malicious-offline-post-without-csrf.puml[]
----
endif::[]

The attacker is similarly blocked from retrieving the CSRF token by the
browser's
https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy[Same-origin
policy]:

ifdef::env-github[]
image::{diagram-path-url}/diagrams/failed-malicious-get-of-csrf.puml[Failed malicious GET of CSRF diagram]
endif::[]

ifndef::env-github[]
[plantuml,align="center"]
----
include::diagrams/failed-malicious-get-of-csrf.puml[]
----
endif::[]
