ifdef::env-github[]
// If on GitHub, define attributes so we can find our diagram files and render
// them.

// The branch will be used to find the correct diagrams to render below.
// When PRing changes to the diagrams you can change this attributes
// temporarily to the name of the branch you're working on. But don't forget
// to change it back to main before merging!!
:github-branch: main

:github-repo: nhsuk/record-childrens-vaccinations

// URL for PlantUML Proxy. Using an attribute mainly because it's just tidier.
:plantuml-proxy-url: http://www.plantuml.com/plantuml/proxy?cache=no&src=

// Full path prefix we'll use for diagrams below.
:diagram-path-url: {plantuml-proxy-url}https://raw.githubusercontent.com/{github-repo}/{github-branch}/docs
endif::[]

:toc:

= Offline support

A key feature required for the Record children's vaccines service is to allow
clinical users to use parts of the system while not connected to the Internet.
There are certain clinical settings where Internet access isn't available, for
example in schools where there may be no mobile signal or WiFi that the SAIS
organisation can use.

To accomplish this the standard patterns provided by server-rendered apps are
insufficient. Aggressive caching can help accommodate viewing data, but updating
records requires a more advanced approach.

== Feature overview

The service's current design is for SAIS organisation members to be able to select
specific programmes to be saved (after being encrypted) for offline use. The user
is then be able to retrieve and view saved patient information, including
consent status and other info (e.g. past vaccination history), before performing
the vaccination. When the vaccination is performed, the event will be recorded
to their local system in an encrypted form. Once reconnected to the Internet,
the records will be uploaded from the local system to the service.

All data saved locally is encrypted using a user-supplied password, which is
only ever stored in memory.

== Technical approach

IMPORTANT: The design of this service feature is still being designed and tested
           with users. The exact approach described here may change, e.g. the
           user may need to manually initiate the synchronisation back to the
           server, etc.

=== Service Worker

The service worker, a feature link:https://caniuse.com/serviceworkers[widely
available in modern browsers], is used to implement the majority of offline
functionality. This service worker sits between the website and the server and
is responsible for the offline functionality. It does this by detecting whether
the browser is online or offline, and implementing caching as appropriate.

ifdef::env-github[]
image::{diagram-path-url}/diagrams/service-worker.puml[Service worker diagram]
endif::[]

ifndef::env-github[]
[plantuml,align="center"]
----
include::diagrams/service-worker.puml[]
----
endif::[]

It contains the logic for preparing to work offline, caching pages and data, and
syncing data back to the server once back online. The following sequence
diagrams illustrate the functionality.

.Using the service while online
Normally when online, requests, while intercepted by the Service worker, go
straight to the server.

ifdef::env-github[]
image::{diagram-path-url}/diagrams/working-online-sequence-diagram.puml[Working online sequence diagram]
endif::[]

ifndef::env-github[]
[plantuml,align="center"]
----
include::diagrams/working-online-sequence-diagram.puml[]
----
endif::[]


.Saving a programme for offline
When the user is ready, they save a programme to be run while offline:

ifdef::env-github[]
image::{diagram-path-url}/diagrams/saving-programme-for-offline-sequence-diagram.puml[Saving programme for offline sequence diagram]
endif::[]

ifndef::env-github[]
[plantuml,align="center"]
----
include::diagrams/saving-programme-for-offline-sequence-diagram.puml[]
----
endif::[]

.Recording vaccinations while offline
When the client goes offline, the Service worker continues to respond to
front-end requests as if still online, but saves the vaccination record to be
synchronised later.

ifdef::env-github[]
image::{diagram-path-url}/diagrams/recording-vaccination-while-offline-sequence-diagram.puml[Working online sequence diagram]
endif::[]

ifndef::env-github[]
[plantuml,align="center"]
----
include::diagrams/recording-vaccination-while-offline-sequence-diagram.puml[]
----
endif::[]

.Record Validation
****
There will be a component of record validation performed in the above steps. In
typical server based apps this happens on the posting of the data; in offline
mode validation is still done by the server, and has to wait until the client is
back online and syncs the data. At this point any errors will be presented to
the user.
****

== Security

Ruby on Rails comes with many security features built-in, such as encryption of
cookie-based session data, protection against CSRF, protection against SQL
injection, etc. These are documented in the
link:https://guides.rubyonrails.org/security.html[Securing Rails
Applications] Rails Guide and aren't covered here.

However, by implementing offline working mode we potentially create new
vulnerabilities. These vulnerabilities, and how we might be able mitigate
against them, are discussed here.

=== Attack scenarios

==== JavaScript accessing cached data

.Attack vectors
* User installs malicious browser extension
* JavaScript injection via unsafe HTTP (non-SSL) connection
* Resource loaded from CDN is compromised.
** We don't use CDN resources.
** We can enable sub-resource integrity.

Our offline implementation doesn't increase our vulnerability because any
JavaScript running in the browser will require that the user visit the service's
website in order to be able to access the cached data (in IndexedDB). In this
situation it doesn't matter if the data is cached locally, as the malicious code
could simply download the data using the user's existing session.

==== JavaScript stealing session

.Attack vectors
* Malicious actor uses JavaScript to steal cookie and use it access the service
  from another browser.
** We can use HttpOnly flag on cookies to disallow access to it from JavaScript.

Our implementation of cached data in the browser does not increase our
vulnerability to this attack. If an attacker steals a session this will give
them access to the data on the server.

==== Physical access to device

.Attack vectors
* Malicious actor gains physical access to the device by a SAIS user, and the
  built-in OS security is weakened (e.g. automatic login enabled or the disk
  isn't encrypted).

Because our implementation of offline working stores data in a local database
that is stored on-disk, if an attacker has physical access to the device they
will be able to access the data stored there. The database used, IndexedDb, does
not provide security measures to mitigate this kind of attack.

As this attack requires physical access, we do consider it partially mitigated,
however there is still residual risk, as described above. We are designing the
service to mitigate the residual risk by implementing a user-provided password
which will be used to encrypt the data before writing it to disk. This approach
involves a non-insignificant burden on the user and the feature is still being
designed. Once we have this designed we will update this documentation.

Additionally, we will remove the data from the database stored on disk once the
vaccination data has been sent (via POST) to the server.

==== Remote root access to device

.Attack vectors
* Malicious actor gains root access to the computer used by the SAIS user,
  either through phishing or other attacks.

If a malicious actor gains root access to a relevant device, there is already
the risk that they would be able to access the service website by piggy-backing
on the SAIS user's session. For example, they may be able to access data on the
server by hijacking the users session, similar to session stealing above.

Additionally, however, and similar to the physical access attack above, a
malicious user with remote root access may be able to find and access the data
that has been stored on disk. We plan to mitigate this the same way as we
mitigate the physical attack vector above, using encryption and removing the
data after sending it to the server.

==== CSRF attack

.Attack vectors
* Malicious actor posts data through the endpoint provided to clients to post
  their data after offline working.

We protect against this attack by implementing a CSRF token that is used
specifically for the offline working mechanism. This ensures that any data
posted to the server after offline working has a valid CSRF token. This attack
and our approach to protecting against it is detailed in the
link:offline-csrf-security.adoc[Offline CSRF Security doc].
