name: Call end-to-end tests

on:
  workflow_call:
    inputs:
      cross_service_tests:
        required: true
        type: boolean
      endpoint:
        required: true
        type: string
      github_ref:
        required: true
        type: string

jobs:
  call-tests:
    # yamllint disable-line rule:line-length
    uses: NHSDigital/manage-vaccinations-in-schools-testing/.github/workflows/end-to-end-tests.yaml@main
    with:
      cross_service_tests: ${{ inputs.cross_service_tests }}
      github_ref: ${{ inputs.github_ref }}
      endpoint: ${{ inputs.endpoint }}
    secrets:
      HTTP_AUTH_TOKEN_FOR_TESTS: ${{ secrets.HTTP_AUTH_TOKEN_FOR_TESTS }}
      MAVIS_TESTING_REPO_ACCESS_TOKEN: ${{ secrets.MAVIS_TESTING_REPO_ACCESS_TOKEN }}
