name: Deploy next
run-name: >-
  ${{ github.event_name == 'workflow_dispatch'
      && format('Copilot ({0})', inputs.environment)
      || 'Copilot (qa and test)' }}

on:
  push:
    branches: [next]
  workflow_dispatch:
    inputs:
      environment:
        description: Deployment environment
        required: true
        type: choice
        options: [qa, test]

jobs:
  Deploy:
    strategy:
      fail-fast: false
      matrix:
        environment: >-
          ${{ fromJSON(github.event_name == 'workflow_dispatch'
              && format('["{0}"]', inputs.environment)
              || '["qa", "test"]') }}
    uses: ./.github/workflows/_deploy-template.yml
    with:
      environment: ${{ matrix.environment }}
