name: Deploy application
run-name: Deploy application to ${{ inputs.environment }}

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Deployment environment
        required: true
        type: choice
        options:
          - qa
          - test
          - preview
          - training
          - production
          - sandbox-alpha
          - sandbox-beta
      server-types:
        description: Server types to deploy
        required: true
        type: choice
        options:
          - all
          - web
          - sidekiq
        default: all
      git-ref-to-deploy:
        description: The git commit SHA to deploy.
        required: false
        type: string
      image-tag:
        description: Docker image tag to deploy (if not provided, will build from git-ref-to-deploy)
        required: false
        type: string
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      server-types:
        required: true
        type: string
      git-ref-to-deploy:
        description: The git commit SHA to deploy.
        required: true
        type: string
      image-tag:
        description: Docker image tag to deploy
        required: false
        type: string

permissions: {}

concurrency:
  group: deploy-application-${{ inputs.environment }}

env:
  aws-role: ${{ inputs.environment == 'production'
    && 'arn:aws:iam::820242920762:role/GithubDeployECSService'
    || 'arn:aws:iam::393416225559:role/GithubDeployECSService' }}
  aws-account-id: ${{ inputs.environment == 'production' && '820242920762' || '393416225559' }}
  cluster-name: mavis-${{ inputs.environment }}
  app-version: ${{ inputs.git-ref-to-deploy == '' && 'unknown' || inputs.git-ref-to-deploy }}

jobs:
  determine-git-sha:
    runs-on: ubuntu-latest
    permissions: {}
    outputs:
      git-sha: ${{ steps.get-git-sha.outputs.git-sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          ref: ${{ inputs.git-ref-to-deploy || github.sha }}
      - name: Get git sha
        id: get-git-sha
        run: echo "git-sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

  build-and-push-image:
    if: ${{ !inputs.image-tag }}
    permissions:
      id-token: write
    needs: determine-git-sha
    uses: ./.github/workflows/build-and-push-image.yml
    with:
      git-sha: ${{ needs.determine-git-sha.outputs.git-sha }}

  prepare-deployment:
    name: Prepare deployment
    runs-on: ubuntu-latest
    needs: [determine-git-sha, build-and-push-image]
    if: ${{ always() && (needs.build-and-push-image.result == 'success' || needs.build-and-push-image.result == 'skipped') }}
    permissions:
      id-token: write
    strategy:
      fail-fast: true
      matrix:
        service: ${{ inputs.server-types == 'all' && fromJSON('["web", "sidekiq"]') || fromJSON(format('["{0}"]', inputs.server-types)) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        id: checkout-code
        with:
          ref: ${{ inputs.git-ref-to-deploy || github.sha }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ env.aws-role }}
          aws-region: eu-west-2
      - name: Get image digest
        id: get-image-digest
        run: |
          digest=$(aws ecr describe-images \
            --repository-name mavis/webapp \
            --image-ids imageTag=${{ inputs.image-tag || needs.determine-git-sha.outputs.git-sha }} \
            --query 'imageDetails[0].imageDigest' \
            --output text)
          echo "digest=$digest" >> $GITHUB_OUTPUT
      - name: Populate web task definition
        id: create-task-definition
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition-family: "mavis-${{ matrix.service }}-task-definition-${{ inputs.environment }}-template"
          container-name: "application"
          image: "${{ env.aws-account-id }}.dkr.ecr.eu-west-2.amazonaws.com/mavis/webapp@${{ steps.get-image-digest.outputs.digest }}"
      - name: Rename task definition file
        run: mv ${{ steps.create-task-definition.outputs.task-definition }} ${{ runner.temp }}/${{ matrix.service }}-task-definition.json
      - name: Upload artifact for ${{ matrix.service }} task definition
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.environment }}-${{ matrix.service }}-task-definition
          path: ${{ runner.temp }}/${{ matrix.service }}-task-definition.json

  approve-deployments:
    name: Wait for approval if required
    runs-on: ubuntu-latest
    needs: prepare-deployment
    environment: ${{ inputs.environment }}
    steps:
      - run: echo "Proceeding with deployment to ${{ inputs.environment }} environment"

  deploy-web:
    name: Deploy web service
    runs-on: ubuntu-latest
    if: ${{ inputs.server-types == 'web' || inputs.server-types == 'all' }}
    needs: [prepare-deployment, approve-deployments]
    permissions:
      id-token: write
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ env.aws-role }}
          aws-region: eu-west-2
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Download web task definition artifact
        uses: actions/download-artifact@v5
        with:
          path: ${{ runner.temp }}
          name: ${{ inputs.environment }}-web-task-definition
      - name: Change family of task definition
        run: |
          file_path="${{ runner.temp }}/web-task-definition.json"
          family_name="mavis-web-task-definition-${{ inputs.environment }}"
          echo "$(jq --arg f "$family_name" '.family = $f' "$file_path")" > "$file_path"
      - name: Register web task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ runner.temp }}/web-task-definition.json
      - name: Deploy web service with CodeDeploy
        id: deploy-web-service
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ runner.temp }}/web-task-definition.json
          codedeploy-appspec: config/templates/appspec.yaml
          cluster: ${{ env.cluster-name }}
          service: mavis-${{ inputs.environment }}-web
          codedeploy-application: mavis-${{ inputs.environment }}
          codedeploy-deployment-group: blue-green-group-${{ inputs.environment }}
      - name: Wait for deployment to complete
        run: |
          echo "Waiting for CodeDeploy deployment ${{ steps.deploy-web-service.outputs.codedeploy-deployment-id }} to complete..."
          aws deploy wait deployment-successful --deployment-id "${{ steps.deploy-web-service.outputs.codedeploy-deployment-id }}"
          echo "Deployment successful"

  deploy-sidekiq:
    name: Deploy sidekiq service
    runs-on: ubuntu-latest
    if: ${{ inputs.server-types == 'sidekiq' || inputs.server-types == 'all' }}
    needs: [prepare-deployment, approve-deployments]
    permissions:
      id-token: write
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ env.aws-role }}
          aws-region: eu-west-2
      - name: Download sidekiq task definition artifact
        uses: actions/download-artifact@v5
        with:
          path: ${{ runner.temp }}
          name: ${{ inputs.environment }}-sidekiq-task-definition
      - name: Change family of task definition
        run: |
          file_path="${{ runner.temp }}/sidekiq-task-definition.json"
          family_name="mavis-sidekiq-task-definition-${{ inputs.environment }}"
          echo "$(jq --arg f "$family_name" '.family = $f' "$file_path")" > "$file_path"
      - name: Deploy sidekiq service
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ runner.temp }}/sidekiq-task-definition.json
          cluster: ${{ env.cluster-name }}
          service: mavis-${{ inputs.environment }}-sidekiq
          force-new-deployment: true
          wait-for-service-stability: true
